const fonts = [
    { value: "Arial", label: "Arial" },
    { value: "Times New Roman", label: "Times New Roman" },
    { value: "Helvetica", label: "Helvetica" },
    { value: "Courier New", label: "Courier New" },
    { value: "Georgia", label: "Georgia" },
    { value: "Verdana", label: "Verdana" },
    { value: "Impact", label: "Impact" },
    { value: "Trebuchet MS", label: "Trebuchet MS" },
    { value: "Comic Sans MS", label: "Comic Sans MS" },
    { value: "Lucida Console", label: "Lucida Console" },
    { value: "Tahoma", label: "Tahoma" },
    { value: "Palatino Linotype", label: "Palatino Linotype" },
    { value: "Arial Black", label: "Arial Black" },
    { value: "Gill Sans", label: "Gill Sans" },
    { value: "Cambria", label: "Cambria" },
    { value: "Garamond", label: "Garamond" },
    { value: "Bookman", label: "Bookman" },
    { value: "Candara", label: "Candara" },
    { value: "Franklin Gothic Medium", label: "Franklin Gothic Medium" },
    { value: "Lucida Sans Unicode", label: "Lucida Sans Unicode" },
    { value: "Futura", label: "Futura" },
    { value: "Perpetua", label: "Perpetua" },
    { value: "Century Gothic", label: "Century Gothic" },
    { value: "Brush Script MT", label: "Brush Script MT" },
    { value: "Calibri", label: "Calibri" },
    { value: "Segoe UI", label: "Segoe UI" },
    { value: "Rockwell", label: "Rockwell" },
    { value: "Baskerville", label: "Baskerville" },
    { value: "Optima", label: "Optima" },
    { value: "Copperplate", label: "Copperplate" },
    { value: "Didot", label: "Didot" },
    { value: "Century Schoolbook", label: "Century Schoolbook" },
    { value: "Consolas", label: "Consolas" },
    { value: "Segoe Print", label: "Segoe Print" },
    { value: "Segoe Script", label: "Segoe Script" },
    { value: "Lucida Handwriting", label: "Lucida Handwriting" },
    { value: "Monaco", label: "Monaco" },
    { value: "Papyrus", label: "Papyrus" },
    { value: "Andale Mono", label: "Andale Mono" },
    { value: "Avant Garde", label: "Avant Garde" },
    { value: "American Typewriter", label: "American Typewriter" },
    { value: "Chalkboard", label: "Chalkboard" },
    { value: "Chalkduster", label: "Chalkduster" },
    { value: "Gill Sans MT", label: "Gill Sans MT" },
    { value: "Herculanum", label: "Herculanum" },
    { value: "Hoefler Text", label: "Hoefler Text" },
    { value: "Zapfino", label: "Zapfino" },
    { value: "Playfair Display", label: "Playfair Display" },
    { value: "PT Serif", label: "PT Serif" },
    { value: "Raleway", label: "Raleway" },
    { value: "Lora", label: "Lora" },
    { value: "Roboto", label: "Roboto" },
    { value: "Open Sans", label: "Open Sans" },
    { value: "Merriweather", label: "Merriweather" },
    { value: "Oswald", label: "Oswald" },
    { value: "Lato", label: "Lato" },
    { value: "Montserrat", label: "Montserrat" },
    { value: "Ubuntu", label: "Ubuntu" },
    { value: "Droid Sans", label: "Droid Sans" },
    { value: "Droid Serif", label: "Droid Serif" },
    { value: "Exo", label: "Exo" },
    { value: "Titillium Web", label: "Titillium Web" },
    { value: "Quicksand", label: "Quicksand" },
    { value: "Pacifico", label: "Pacifico" },
    { value: "Cabin", label: "Cabin" },
    { value: "Indie Flower", label: "Indie Flower" }
  ];
  
  export default fonts;
  